### ISSUE TITLE
No suggestions for keep.google.com

### ISSUE THREAD

**Issue by QAInsights** [sarthology/nomoogle#3]
**Steps to reproduce**

1. Visit [keep.google.com](keep.google.com) in Firefox

**Actual results**
Nomoogle is not showing any alternatives.

**Expected results**
Nomoogle could show Taskade, Notion.so, Microsoft ToDo etc

**Comment by marcus-sa** [comment]
Never really got the point in recommending Microsoft over Google.
They're almost both equally as big monopolies, only difference is that Microsoft products are 10x worse.

**Comment by QAInsights** [comment]
Yes, I didn't update the json file with the Microsoft Todo. Just added Notion and Taskade.
